import type { Product } from "../model/types";

// 디자인 :1440-1449(PRODUCTS)+:1430-1439(PROD_DESC) 이식. 8건 전부, desc는 PROD_DESC를 id로 병합.
const PRODUCTS: Product[] = [
  {
    id: "choco",
    cat: "food",
    price: 12000,
    status: "allowed",
    color: "#FFF1E6",
    iconColor: "#E8820E",
    icon: "heart",
    name: {
      ko: "제주 감귤 초콜릿",
      en: "Jeju Tangerine Chocolate",
      zh: "济州柑橘巧克力",
      ja: "済州みかんチョコ",
    },
    desc: {
      ko: "감귤 과즙을 넣은 달콤한 밀크초콜릿",
      en: "Sweet milk chocolate with tangerine",
      zh: "加入柑橘果汁的香甜巧克力",
      ja: "みかん果汁入りの甘いチョコ",
    },
    customs: {
      ko: "포장 과자류 — 반입 제한 없음.",
      en: "Packaged confectionery — no restriction.",
      zh: "包装糖果——无限制。",
      ja: "包装菓子——制限なし。",
    },
    line: {
      ko: "선사 반입 제한 없음.",
      en: "No cruise line limit.",
      zh: "邮轮无限制。",
      ja: "船社制限なし。",
    },
  },
  {
    id: "hallabong",
    cat: "food",
    price: 25000,
    status: "restricted",
    color: "#FFEFD6",
    iconColor: "#E8820E",
    icon: "sun",
    name: {
      ko: "한라봉 (생과일)",
      en: "Hallabong Citrus (fresh)",
      zh: "汉拿峰（鲜果）",
      ja: "ハルラボン(生果実)",
    },
    desc: {
      ko: "제주 대표 감귤, 상큼한 생과일",
      en: "Jeju's signature juicy citrus",
      zh: "济州代表柑橘，清新鲜果",
      ja: "済州代表のみかん、爽やかな生果実",
    },
    customs: {
      ko: "생과일 — 다수 국가 검역·반입 제한.",
      en: "Fresh fruit — quarantine/import limits in many countries.",
      zh: "鲜果——多国检疫限制。",
      ja: "生果実——多くの国で検疫制限。",
    },
    line: {
      ko: "당일 선내 취식용만 허용.",
      en: "Onboard same-day consumption only.",
      zh: "仅限当日船上食用。",
      ja: "当日船内消費のみ可。",
    },
  },
  {
    id: "omegi",
    cat: "food",
    price: 18000,
    status: "restricted",
    color: "#EAF7EE",
    iconColor: "#12A150",
    icon: "coffee",
    name: {
      ko: "제주 오메기떡",
      en: "Jeju Omegi Rice Cake",
      zh: "济州艾饼",
      ja: "済州オメギ餅",
    },
    desc: {
      ko: "차조로 빚은 쫀득한 전통 떡",
      en: "Chewy traditional millet rice cake",
      zh: "糯米制成的传统年糕",
      ja: "もちもちの伝統餅",
    },
    customs: {
      ko: "신선 식품 — 당일 소비, 반입 부적합.",
      en: "Perishable — same-day, not for import.",
      zh: "易腐——当日食用，不宜携带。",
      ja: "生鮮——当日消費、持込不可。",
    },
    line: {
      ko: "선내 냉장 보관 제한.",
      en: "Limited refrigeration onboard.",
      zh: "船上冷藏有限。",
      ja: "船内冷蔵は限定的。",
    },
  },
  {
    id: "cosme",
    cat: "cosmetics",
    price: 39000,
    status: "allowed",
    color: "#F3ECFF",
    iconColor: "#8B3FF0",
    icon: "sparkleFill",
    name: {
      ko: "백년초 화장품 세트",
      en: "Baengnyeoncho Cosmetics",
      zh: "仙人掌护肤套装",
      ja: "化粧品セット",
    },
    desc: {
      ko: "백년초 성분의 수분 스킨케어 세트",
      en: "Hydrating prickly-pear skincare set",
      zh: "仙人掌成分保湿护肤套装",
      ja: "うるおいスキンケアセット",
    },
    customs: {
      ko: "화장품 — 자가 사용 한도 내.",
      en: "Cosmetics within personal-use limits.",
      zh: "化妆品——个人自用限额内。",
      ja: "化粧品——自己使用範囲内。",
    },
    line: {
      ko: "액체류 객실 반입 한도 내.",
      en: "Liquids within cabin allowance.",
      zh: "液体在客舱限额内。",
      ja: "液体は客室許容内。",
    },
  },
  {
    id: "beer",
    cat: "alcohol",
    price: 21000,
    status: "conditional",
    color: "#FFF6D6",
    iconColor: "#C08A00",
    icon: "coins",
    name: {
      ko: "제주 감귤 수제맥주",
      en: "Jeju Tangerine Beer",
      zh: "济州柑橘精酿",
      ja: "済州みかんビール",
    },
    desc: {
      ko: "감귤 향이 상큼한 제주 수제맥주",
      en: "Craft beer with a citrus finish",
      zh: "柑橘香气的济州精酿",
      ja: "みかん香る済州クラフトビール",
    },
    customs: {
      ko: "주류 — 면세 한도 내 반입.",
      en: "Alcohol within duty-free allowance.",
      zh: "酒类——免税限额内。",
      ja: "酒類——免税範囲内。",
    },
    line: {
      ko: "미개봉 상태로 승선 시 승무원 보관.",
      en: "Sealed; handed to crew at boarding.",
      zh: "未开封，登船时交船员保管。",
      ja: "未開封で乗船時に乗務員預け。",
    },
  },
  {
    id: "jerky",
    cat: "food",
    price: 22000,
    status: "prohibited",
    color: "#FDE7E7",
    iconColor: "#E23B3B",
    icon: "circleClose",
    name: {
      ko: "제주 흑돼지 육포",
      en: "Jeju Black Pork Jerky",
      zh: "济州黑猪肉干",
      ja: "済州黒豚ジャーキー",
    },
    desc: {
      ko: "흑돼지로 만든 짭짤한 수제 육포",
      en: "Savory Jeju black-pork jerky",
      zh: "黑猪制成的咸香肉干",
      ja: "黒豚の旨塩ジャーキー",
    },
    customs: {
      ko: "육류 가공품 — 대부분 국가 반입 금지.",
      en: "Processed meat — import banned in most destinations.",
      zh: "肉类加工品——多数国家禁止。",
      ja: "食肉加工品——多くの国で持込禁止。",
    },
    line: {
      ko: "선내 육류 반입 불가.",
      en: "Meat products not permitted onboard.",
      zh: "船内禁止携带肉类。",
      ja: "船内への肉類持込不可。",
    },
  },
  {
    id: "tea",
    cat: "souvenir",
    price: 28000,
    status: "allowed",
    color: "#E7F6EC",
    iconColor: "#12A150",
    icon: "coffee",
    name: {
      ko: "제주 녹차 선물세트",
      en: "Jeju Green Tea Gift Set",
      zh: "济州绿茶礼盒",
      ja: "済州緑茶ギフト",
    },
    desc: {
      ko: "제주 유기농 녹차 선물세트",
      en: "Organic Jeju green tea gift set",
      zh: "济州有机绿茶礼盒",
      ja: "済州オーガニック緑茶ギフト",
    },
    customs: {
      ko: "건조 차류 — 반입 제한 없음.",
      en: "Dried tea — no restriction.",
      zh: "干茶——无限制。",
      ja: "乾燥茶——制限なし。",
    },
    line: {
      ko: "선사 반입 제한 없음.",
      en: "No cruise line limit.",
      zh: "邮轮无限制。",
      ja: "船社制限なし。",
    },
  },
  {
    id: "diffuser",
    cat: "souvenir",
    price: 32000,
    status: "allowed",
    color: "#E7F1FF",
    iconColor: "#0066FF",
    icon: "template",
    name: {
      ko: "제주 오름 디퓨저",
      en: "Jeju Oreum Diffuser",
      zh: "济州岳香薰",
      ja: "済州オルム·ディフューザー",
    },
    desc: {
      ko: "제주 오름의 숲향을 담은 디퓨저",
      en: "Diffuser scented like Jeju's forests",
      zh: "济州森林香氛香薰",
      ja: "済州の森の香りのディフューザー",
    },
    customs: {
      ko: "비식품 잡화 — 반입 제한 없음.",
      en: "Non-food goods — no restriction.",
      zh: "非食品——无限制。",
      ja: "非食品——制限なし。",
    },
    line: {
      ko: "인화성 액체 용량 한도 내.",
      en: "Flammable-liquid volume within limit.",
      zh: "易燃液体在限量内。",
      ja: "引火性液体は制限内。",
    },
  },
];

export const listGoods = async (opts?: { category?: string }): Promise<Product[]> => {
  const category = opts?.category;
  if (!category || category === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.cat === category);
};
export const getGood = async (id: string): Promise<Product | undefined> =>
  PRODUCTS.find((p) => p.id === id);
