import type { Spot } from "../model/types";

// 디자인 :1416-1429 이식. 12건 전부, x·y·subs 포함.
const SPOTS: Spot[] = [
  {
    id: "dongmun",
    portKey: "jeju",
    km: 2.0,
    min: 60,
    x: 38,
    y: 44,
    icon: "coffee",
    color: "#FFF1E6",
    iconColor: "#E8820E",
    themes: ["food", "attraction"],
    name: { ko: "제주 동문시장", en: "Dongmun Market", zh: "东门市场", ja: "東門市場" },
    cat: { ko: "전통시장", en: "Market", zh: "传统市场", ja: "伝統市場" },
    blurb: {
      ko: "항구에서 가장 가까운 제주 대표 재래시장. 흑돼지·회·간식거리가 가득해요.",
      en: "Jeju's liveliest market, closest to the port — black pork, sashimi and street snacks.",
      zh: "距港口最近的济州代表市场，黑猪、生鱼片、小吃应有尽有。",
      ja: "港から最も近い済州の代表市場。黒豚·刺身·屋台グルメが満載。",
    },
    subs: [
      {
        name: { ko: "동문 흑돼지 골목", en: "Black Pork Alley", zh: "黑猪街", ja: "黒豚横丁" },
        type: { ko: "맛집", en: "Food", zh: "美食", ja: "グルメ" },
        blurb: {
          ko: "제주 흑돼지 구이",
          en: "Grilled Jeju black pork",
          zh: "济州黑猪烤肉",
          ja: "済州黒豚焼き",
        },
      },
      {
        name: { ko: "시장 감귤주스", en: "Tangerine Juice", zh: "柑橘鲜榨", ja: "みかんジュース" },
        type: { ko: "간식", en: "Snack", zh: "小吃", ja: "軽食" },
        blurb: {
          ko: "갓 짠 감귤주스",
          en: "Fresh-pressed juice",
          zh: "现榨柑橘汁",
          ja: "搾りたてジュース",
        },
      },
    ],
  },
  {
    id: "yongduam",
    portKey: "jeju",
    km: 3.5,
    min: 40,
    x: 26,
    y: 32,
    icon: "location",
    color: "#E7F1FF",
    iconColor: "#0066FF",
    themes: ["attraction"],
    name: { ko: "용두암", en: "Yongduam Rock", zh: "龙头岩", ja: "龍頭岩" },
    cat: { ko: "자연경관", en: "Nature", zh: "自然景观", ja: "自然景観" },
    blurb: {
      ko: "용의 머리를 닮은 해안 바위. 해안 산책과 사진 명소예요.",
      en: "A dragon-head lava rock on the coast — a classic photo and stroll spot.",
      zh: "形似龙头的海岸岩石，拍照散步胜地。",
      ja: "龍の頭に似た海岸の岩。散策·撮影の名所。",
    },
    subs: [
      {
        name: { ko: "용연 구름다리", en: "Yongyeon Bridge", zh: "龙渊吊桥", ja: "龍淵つり橋" },
        type: { ko: "체험", en: "Walk", zh: "体验", ja: "体験" },
        blurb: {
          ko: "협곡 위 구름다리",
          en: "Bridge over the gorge",
          zh: "峡谷吊桥",
          ja: "渓谷のつり橋",
        },
      },
      {
        name: { ko: "해안 카페", en: "Seaside Cafe", zh: "海岸咖啡", ja: "海岸カフェ" },
        type: { ko: "카페", en: "Cafe", zh: "咖啡", ja: "カフェ" },
        blurb: {
          ko: "오션뷰 커피",
          en: "Ocean-view coffee",
          zh: "海景咖啡",
          ja: "オーシャンビューコーヒー",
        },
      },
    ],
  },
  {
    id: "sarabong",
    portKey: "jeju",
    km: 2.8,
    min: 50,
    x: 62,
    y: 36,
    icon: "sun",
    color: "#F3ECFF",
    iconColor: "#8B3FF0",
    themes: ["attraction"],
    name: { ko: "사라봉 전망", en: "Sarabong Peak", zh: "纱罗峰", ja: "サラボン" },
    cat: { ko: "전망대", en: "Viewpoint", zh: "观景台", ja: "展望" },
    blurb: {
      ko: "제주 시내와 바다를 한눈에 담는 낮은 오름이에요.",
      en: "A gentle hill with sweeping views of the city and the sea.",
      zh: "俯瞰市区与大海的小火山丘。",
      ja: "市街と海を一望できる小さなオルム。",
    },
    subs: [
      {
        name: { ko: "사라봉 정자", en: "Summit Pavilion", zh: "峰顶亭", ja: "頂上の東屋" },
        type: { ko: "전망", en: "View", zh: "观景", ja: "眺望" },
        blurb: { ko: "일몰 명소", en: "Sunset viewpoint", zh: "日落景点", ja: "夕日スポット" },
      },
      {
        name: {
          ko: "별도봉 산책로",
          en: "Byeoldobong Trail",
          zh: "别刀峰步道",
          ja: "ビョルド遊歩道",
        },
        type: { ko: "체험", en: "Walk", zh: "体验", ja: "体験" },
        blurb: { ko: "해안 절벽길", en: "Coastal cliff walk", zh: "海岸悬崖路", ja: "海岸の崖道" },
      },
    ],
  },
  {
    id: "samyang",
    portKey: "jeju",
    km: 6.0,
    min: 45,
    x: 74,
    y: 50,
    icon: "umbrella",
    color: "#E7F6EC",
    iconColor: "#12A150",
    themes: ["attraction"],
    name: { ko: "삼양 검은모래해변", en: "Samyang Beach", zh: "三阳黑沙滩", ja: "三陽ビーチ" },
    cat: { ko: "해변", en: "Beach", zh: "海滩", ja: "ビーチ" },
    blurb: {
      ko: "검은 화산모래로 유명한 해변. 발 담그기 좋은 곳이에요.",
      en: "Famous black volcanic sand — great for a quick paddle.",
      zh: "以黑色火山沙闻名的海滩。",
      ja: "黒い火山砂で有名なビーチ。",
    },
    subs: [
      {
        name: { ko: "해변 포장마차", en: "Beach Food Cart", zh: "海滩摊", ja: "ビーチ屋台" },
        type: { ko: "간식", en: "Snack", zh: "小吃", ja: "軽食" },
        blurb: { ko: "해물라면", en: "Seafood ramen", zh: "海鲜拉面", ja: "海鮮ラーメン" },
      },
      {
        name: { ko: "검은모래 찜질", en: "Sand Therapy", zh: "黑沙浴", ja: "砂療法" },
        type: { ko: "체험", en: "Experience", zh: "体验", ja: "体験" },
        blurb: { ko: "여름 모래찜질", en: "Summer sand bathing", zh: "夏季沙浴", ja: "夏の砂風呂" },
      },
    ],
  },
  {
    id: "pkgjeju",
    portKey: "jeju",
    km: 1.2,
    min: 15,
    x: 16,
    y: 58,
    icon: "location",
    color: "#E7F1FF",
    iconColor: "#0066FF",
    themes: ["package"],
    name: {
      ko: "제주 동부 일주 반일 투어",
      en: "East Jeju Half-day Tour",
      zh: "济州东部半日游",
      ja: "済州東部半日ツアー",
    },
    cat: { ko: "여행사 상품 · 5시간", en: "Tour · 5h", zh: "旅行社产品·5小时", ja: "ツアー·5時間" },
    blurb: {
      ko: "성산일출봉·섭지코지를 도는 가이드 동반 반일 투어 상품이에요. 크루즈 출항 시간에 맞춰 진행돼요.",
      en: "A guided half-day tour of Seongsan and Seopjikoji, timed to your ship's departure.",
      zh: "含导游的东部半日游，配合邮轮离港时间。",
      ja: "城山·渉地岬を巡るガイド付き半日ツアー。出航時間に合わせて運行。",
    },
    subs: [],
  },
  {
    id: "cafejeju",
    portKey: "jeju",
    km: 4.0,
    min: 35,
    x: 20,
    y: 52,
    icon: "coffee",
    color: "#F3ECFF",
    iconColor: "#8B3FF0",
    themes: ["cafe"],
    name: {
      ko: "애월 오션뷰 카페",
      en: "Aewol Ocean Café",
      zh: "涯月海景咖啡",
      ja: "涯月オーシャンカフェ",
    },
    cat: { ko: "카페", en: "Café", zh: "咖啡", ja: "カフェ" },
    blurb: {
      ko: "에메랄드빛 바다를 배경으로 감귤 라떼를 즐기는 인기 카페예요.",
      en: "A popular seaside café for a tangerine latte over emerald water.",
      zh: "面朝翡翠海的人气咖啡馆，招牌柑橘拿铁。",
      ja: "エメラルドの海を望む人気カフェ。みかんラテが名物。",
    },
    subs: [],
  },
  {
    id: "cheonjiyeon",
    portKey: "gangjeong",
    km: 4.5,
    min: 40,
    x: 38,
    y: 60,
    icon: "umbrella",
    color: "#E7F6EC",
    iconColor: "#12A150",
    themes: ["attraction"],
    name: { ko: "천지연폭포", en: "Cheonjiyeon Falls", zh: "天地渊瀑布", ja: "天地淵の滝" },
    cat: { ko: "자연", en: "Nature", zh: "自然", ja: "自然" },
    blurb: {
      ko: "울창한 숲길 끝의 웅장한 폭포. 야간 조명도 아름다워요.",
      en: "A grand waterfall at the end of a lush forest trail.",
      zh: "茂密林道尽头的壮丽瀑布。",
      ja: "緑豊かな遊歩道の先にある壮大な滝。",
    },
    subs: [
      {
        name: { ko: "서귀포 칠십리", en: "Chilsimni Park", zh: "七十里公园", ja: "七十里公園" },
        type: { ko: "체험", en: "Walk", zh: "体验", ja: "体験" },
        blurb: {
          ko: "해안 공원 산책",
          en: "Coastal park walk",
          zh: "海岸公园",
          ja: "海岸公園散策",
        },
      },
      {
        name: { ko: "감귤 카페", en: "Citrus Cafe", zh: "柑橘咖啡", ja: "みかんカフェ" },
        type: { ko: "카페", en: "Cafe", zh: "咖啡", ja: "カフェ" },
        blurb: { ko: "한라봉 에이드", en: "Hallabong ade", zh: "汉拿峰饮", ja: "ハルラボンエード" },
      },
    ],
  },
  {
    id: "jeongbang",
    portKey: "gangjeong",
    km: 5.0,
    min: 40,
    x: 58,
    y: 64,
    icon: "location",
    color: "#E7F1FF",
    iconColor: "#0066FF",
    themes: ["attraction"],
    name: { ko: "정방폭포", en: "Jeongbang Falls", zh: "正房瀑布", ja: "正房の滝" },
    cat: { ko: "자연", en: "Nature", zh: "自然", ja: "自然" },
    blurb: {
      ko: "바다로 직접 떨어지는 아시아 유일의 해안 폭포예요.",
      en: "One of Asia's few waterfalls plunging straight into the sea.",
      zh: "亚洲罕见直落入海的瀑布。",
      ja: "海へ直接落ちるアジア唯一級の滝。",
    },
    subs: [
      {
        name: {
          ko: "소정방 포토존",
          en: "Sojeongbang Photo",
          zh: "小正房拍照点",
          ja: "小正房撮影",
        },
        type: { ko: "전망", en: "View", zh: "观景", ja: "眺望" },
        blurb: { ko: "절벽 포토존", en: "Cliffside photos", zh: "悬崖拍照", ja: "崖の撮影" },
      },
      {
        name: { ko: "서복전시관", en: "Seobok Museum", zh: "徐福展馆", ja: "徐福展示館" },
        type: { ko: "체험", en: "Culture", zh: "文化", ja: "文化" },
        blurb: { ko: "역사 전시", en: "History exhibit", zh: "历史展", ja: "歴史展示" },
      },
    ],
  },
  {
    id: "olle",
    portKey: "gangjeong",
    km: 4.8,
    min: 60,
    x: 46,
    y: 72,
    icon: "coffee",
    color: "#FFF1E6",
    iconColor: "#E8820E",
    themes: ["food", "attraction"],
    name: {
      ko: "서귀포 매일올레시장",
      en: "Seogwipo Olle Market",
      zh: "西归浦偶来市场",
      ja: "西帰浦オルレ市場",
    },
    cat: { ko: "전통시장", en: "Market", zh: "传统市场", ja: "伝統市場" },
    blurb: {
      ko: "남부 최대 재래시장. 감귤·오메기떡·회국수가 유명해요.",
      en: "The south's biggest market — tangerines, omegi cake and noodle stalls.",
      zh: "南部最大市场，柑橘、艾饼、面食有名。",
      ja: "南部最大の市場。みかん·オメギ餅·麺が有名。",
    },
    subs: [
      {
        name: { ko: "회국수 노포", en: "Sashimi Noodles", zh: "生鱼片面", ja: "刺身うどん" },
        type: { ko: "맛집", en: "Food", zh: "美食", ja: "グルメ" },
        blurb: {
          ko: "제주식 회국수",
          en: "Jeju sashimi noodles",
          zh: "济州生鱼片面",
          ja: "済州式刺身麺",
        },
      },
      {
        name: { ko: "오메기떡 명가", en: "Omegi Cake House", zh: "艾饼名家", ja: "オメギ餅の店" },
        type: { ko: "간식", en: "Snack", zh: "小吃", ja: "軽食" },
        blurb: {
          ko: "수제 오메기떡",
          en: "Handmade omegi cake",
          zh: "手工艾饼",
          ja: "手作りオメギ餅",
        },
      },
    ],
  },
  {
    id: "jusangjeolli",
    portKey: "gangjeong",
    km: 8.0,
    min: 50,
    x: 66,
    y: 68,
    icon: "sun",
    color: "#F3ECFF",
    iconColor: "#8B3FF0",
    themes: ["attraction"],
    name: { ko: "대포 주상절리대", en: "Jusangjeolli Cliff", zh: "柱状节理带", ja: "柱状節理帯" },
    cat: { ko: "경관", en: "Nature", zh: "景观", ja: "景観" },
    blurb: {
      ko: "육각형 현무암 기둥이 늘어선 해안 절벽 명소예요.",
      en: "Dramatic hexagonal basalt columns along the coast.",
      zh: "六角玄武岩柱排列的海岸奇观。",
      ja: "六角形の玄武岩柱が並ぶ海岸の名所。",
    },
    subs: [
      {
        name: { ko: "중문 색달해변", en: "Jungmun Beach", zh: "中文海滩", ja: "中文ビーチ" },
        type: { ko: "해변", en: "Beach", zh: "海滩", ja: "ビーチ" },
        blurb: { ko: "서핑 해변", en: "Surf beach", zh: "冲浪海滩", ja: "サーフビーチ" },
      },
      {
        name: {
          ko: "대포 해안 카페",
          en: "Daepo Coast Cafe",
          zh: "大浦海岸咖啡",
          ja: "大浦海岸カフェ",
        },
        type: { ko: "카페", en: "Cafe", zh: "咖啡", ja: "カフェ" },
        blurb: { ko: "절벽뷰 카페", en: "Cliff-view cafe", zh: "悬崖景咖啡", ja: "崖ビューカフェ" },
      },
    ],
  },
  {
    id: "pkggj",
    portKey: "gangjeong",
    km: 1.0,
    min: 15,
    x: 20,
    y: 84,
    icon: "location",
    color: "#E7F1FF",
    iconColor: "#0066FF",
    themes: ["package"],
    name: {
      ko: "서귀포 서부 명소 투어",
      en: "West Seogwipo Sights Tour",
      zh: "西归浦西部景点游",
      ja: "西帰浦西部名所ツアー",
    },
    cat: { ko: "여행사 상품 · 5시간", en: "Tour · 5h", zh: "旅行社产品·5小时", ja: "ツアー·5時間" },
    blurb: {
      ko: "오설록·카멜리아힐을 도는 가이드 반일 투어 상품이에요. 픽업·드롭이 포함돼요.",
      en: "A guided half-day tour of Osulloc and Camellia Hill with pickup and drop-off.",
      zh: "含接送的西部半日游，游览茶园与山茶花园。",
      ja: "オソルロク·椿の丘を巡る送迎付き半日ツアー。",
    },
    subs: [],
  },
  {
    id: "cafegj",
    portKey: "gangjeong",
    km: 3.2,
    min: 35,
    x: 52,
    y: 56,
    icon: "coffee",
    color: "#F3ECFF",
    iconColor: "#8B3FF0",
    themes: ["cafe"],
    name: {
      ko: "서귀포 감귤밭 카페",
      en: "Seogwipo Citrus Café",
      zh: "西归浦柑橘咖啡",
      ja: "西帰浦みかん畑カフェ",
    },
    cat: { ko: "카페", en: "Café", zh: "咖啡", ja: "カフェ" },
    blurb: {
      ko: "감귤밭 한가운데에서 디저트와 커피를 즐기는 감성 카페예요.",
      en: "A cozy café set right in a tangerine grove.",
      zh: "坐落柑橘园中的文艺咖啡馆。",
      ja: "みかん畑の中の癒しカフェ。",
    },
    subs: [],
  },
];

export const listSpots = async ({ portKey }: { portKey: Spot["portKey"] }): Promise<Spot[]> =>
  SPOTS.filter((s) => s.portKey === portKey);
export const getSpot = async (id: string): Promise<Spot | undefined> =>
  SPOTS.find((s) => s.id === id);
