/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CruiseRouteImport } from './routes/cruise'
import { Route as PayDemoRouteImport } from './routes/pay-demo'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppConceptRouteImport } from './routes/app/concept'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppFinalRouteImport } from './routes/app/final'
import { Route as AppMapRouteImport } from './routes/app/map'
import { Route as AppMoveRouteImport } from './routes/app/move'
import { Route as AppMyRouteImport } from './routes/app/my'
import { Route as AppPackageRouteImport } from './routes/app/package'
import { Route as AppShopRouteImport } from './routes/app/shop'
import { Route as AppThemeRouteImport } from './routes/app/theme'
import { Route as AppTransportRouteImport } from './routes/app/transport'
import { Route as AppProductProductIdRouteImport } from './routes/app/product.$productId'
import { Route as AppSpotSpotIdRouteImport } from './routes/app/spot.$spotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseRoute = CruiseRouteImport.update({
  id: '/cruise',
  path: '/cruise',
  getParentRoute: () => rootRouteImport,
} as any)
const PayDemoRoute = PayDemoRouteImport.update({
  id: '/pay-demo',
  path: '/pay-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConceptRoute = AppConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppFinalRoute = AppFinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppMoveRoute = AppMoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRoute = AppMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AppRoute,
} as any)
const AppPackageRoute = AppPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppThemeRoute = AppThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppProductProductIdRoute = AppProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppSpotSpotIdRoute = AppSpotSpotIdRouteImport.update({
  id: '/spot/$spotId',
  path: '/spot/$spotId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cruise': typeof CruiseRoute
  '/pay-demo': typeof PayDemoRoute
  '/app/concept': typeof AppConceptRoute
  '/app/explore': typeof AppExploreRoute
  '/app/final': typeof AppFinalRoute
  '/app/map': typeof AppMapRoute
  '/app/move': typeof AppMoveRoute
  '/app/my': typeof AppMyRoute
  '/app/package': typeof AppPackageRoute
  '/app/shop': typeof AppShopRoute
  '/app/theme': typeof AppThemeRoute
  '/app/transport': typeof AppTransportRoute
  '/app/': typeof AppIndexRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
  '/app/spot/$spotId': typeof AppSpotSpotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/cruise': typeof CruiseRoute
  '/pay-demo': typeof PayDemoRoute
  '/app/concept': typeof AppConceptRoute
  '/app/explore': typeof AppExploreRoute
  '/app/final': typeof AppFinalRoute
  '/app/map': typeof AppMapRoute
  '/app/move': typeof AppMoveRoute
  '/app/my': typeof AppMyRoute
  '/app/package': typeof AppPackageRoute
  '/app/shop': typeof AppShopRoute
  '/app/theme': typeof AppThemeRoute
  '/app/transport': typeof AppTransportRoute
  '/app': typeof AppIndexRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
  '/app/spot/$spotId': typeof AppSpotSpotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cruise': typeof CruiseRoute
  '/pay-demo': typeof PayDemoRoute
  '/app/concept': typeof AppConceptRoute
  '/app/explore': typeof AppExploreRoute
  '/app/final': typeof AppFinalRoute
  '/app/map': typeof AppMapRoute
  '/app/move': typeof AppMoveRoute
  '/app/my': typeof AppMyRoute
  '/app/package': typeof AppPackageRoute
  '/app/shop': typeof AppShopRoute
  '/app/theme': typeof AppThemeRoute
  '/app/transport': typeof AppTransportRoute
  '/app/': typeof AppIndexRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
  '/app/spot/$spotId': typeof AppSpotSpotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/cruise'
    | '/pay-demo'
    | '/app/concept'
    | '/app/explore'
    | '/app/final'
    | '/app/map'
    | '/app/move'
    | '/app/my'
    | '/app/package'
    | '/app/shop'
    | '/app/theme'
    | '/app/transport'
    | '/app/'
    | '/app/product/$productId'
    | '/app/spot/$spotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/cruise'
    | '/pay-demo'
    | '/app/concept'
    | '/app/explore'
    | '/app/final'
    | '/app/map'
    | '/app/move'
    | '/app/my'
    | '/app/package'
    | '/app/shop'
    | '/app/theme'
    | '/app/transport'
    | '/app'
    | '/app/product/$productId'
    | '/app/spot/$spotId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/cruise'
    | '/pay-demo'
    | '/app/concept'
    | '/app/explore'
    | '/app/final'
    | '/app/map'
    | '/app/move'
    | '/app/my'
    | '/app/package'
    | '/app/shop'
    | '/app/theme'
    | '/app/transport'
    | '/app/'
    | '/app/product/$productId'
    | '/app/spot/$spotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CruiseRoute: typeof CruiseRoute
  PayDemoRoute: typeof PayDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise': {
      id: '/cruise'
      path: '/cruise'
      fullPath: '/cruise'
      preLoaderRoute: typeof CruiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-demo': {
      id: '/pay-demo'
      path: '/pay-demo'
      fullPath: '/pay-demo'
      preLoaderRoute: typeof PayDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/concept': {
      id: '/app/concept'
      path: '/concept'
      fullPath: '/app/concept'
      preLoaderRoute: typeof AppConceptRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/final': {
      id: '/app/final'
      path: '/final'
      fullPath: '/app/final'
      preLoaderRoute: typeof AppFinalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/move': {
      id: '/app/move'
      path: '/move'
      fullPath: '/app/move'
      preLoaderRoute: typeof AppMoveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my': {
      id: '/app/my'
      path: '/my'
      fullPath: '/app/my'
      preLoaderRoute: typeof AppMyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/package': {
      id: '/app/package'
      path: '/package'
      fullPath: '/app/package'
      preLoaderRoute: typeof AppPackageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/theme': {
      id: '/app/theme'
      path: '/theme'
      fullPath: '/app/theme'
      preLoaderRoute: typeof AppThemeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transport': {
      id: '/app/transport'
      path: '/transport'
      fullPath: '/app/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product/$productId': {
      id: '/app/product/$productId'
      path: '/product/$productId'
      fullPath: '/app/product/$productId'
      preLoaderRoute: typeof AppProductProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spot/$spotId': {
      id: '/app/spot/$spotId'
      path: '/spot/$spotId'
      fullPath: '/app/spot/$spotId'
      preLoaderRoute: typeof AppSpotSpotIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConceptRoute: typeof AppConceptRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFinalRoute: typeof AppFinalRoute
  AppMapRoute: typeof AppMapRoute
  AppMoveRoute: typeof AppMoveRoute
  AppMyRoute: typeof AppMyRoute
  AppPackageRoute: typeof AppPackageRoute
  AppShopRoute: typeof AppShopRoute
  AppThemeRoute: typeof AppThemeRoute
  AppTransportRoute: typeof AppTransportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductProductIdRoute: typeof AppProductProductIdRoute
  AppSpotSpotIdRoute: typeof AppSpotSpotIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConceptRoute: AppConceptRoute,
  AppExploreRoute: AppExploreRoute,
  AppFinalRoute: AppFinalRoute,
  AppMapRoute: AppMapRoute,
  AppMoveRoute: AppMoveRoute,
  AppMyRoute: AppMyRoute,
  AppPackageRoute: AppPackageRoute,
  AppShopRoute: AppShopRoute,
  AppThemeRoute: AppThemeRoute,
  AppTransportRoute: AppTransportRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductProductIdRoute: AppProductProductIdRoute,
  AppSpotSpotIdRoute: AppSpotSpotIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CruiseRoute: CruiseRoute,
  PayDemoRoute: PayDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
